### ISSUE TITLE
Issues with pnpm / turbo monorepo

### ISSUE THREAD

**Issue by joshheyse** [monorepolint/monorepolint#198]
Hello. 

I was very excited to find monorepolint! It's exactly what I envisioned. Luckily, I searched before I hauled off and wrote something myself.

Is the latest version 0.4.0?
npmjs (https://www.npmjs.com/package/monorepolint) says the 0.4.0 was last published 16 days ago, but the GitHub releases (https://github.com/monorepolint/monorepolint/releases/tag/v0.4.0) say two years ago? Based on the commits, the project looks active.

I've run into an issue with my setup. (All paths are relative to the monorepo root) 

The monorepolint/mrl not found after `pnpm install -w --save-dev monorepolint`
I would have expected monorepolint & mrl to have been in `node_modules/.bin/`
I'm guessing this is because monorepo doesn't redeclare the bins from @monorepolint/cli
I can work around this by

1. `cd node_modules/monorepolint && npm install && cd - `
2. `./node_modules/monorepolint/node_modules/.bin/monorepolint check `

It also looks like either the Docusaurus documentation or the README.md is out of date (some things reference rules, other checks)

Version:
node: v16.18.1
pnpm: 7.19.0
turbo: 1.6.3

I've uploaded a repo that demonstrates the issue https://github.com/joshheyse/monorepolint-issues.

```
git clone https://github.com/joshheyse/monorepolint-issues.git
cd monorepolint-issues
pnpm install
pnpm exec monorepolint # boom
```

I'd be happy to help out if you are accepting PRs.

**Comment by joshheyse** [comment]
I would also be nice if monorepolint could read the workspaces from the pnpm-workspace.yaml instead of requiring them to be in the root package.json

**Comment by ericanderson** [comment]
Hey! Thanks for the feedback.

MRL is something we use internally where I work and we generally take nightlies (look on npm website for alpha builds). I also use the nightly for this repo itself as well as some other projects. 

It's my intent to release a new version soon. If you are getting started figuring things out on the alphas will be easier because I changed a lot since the 0.4 for performance and ease of use so custom rules for 0.4 will need to be rewritten. 

Feel free to keep this issue open!

**Comment by ericanderson** [comment]
Hey @joshheyse , I've done some development as of late so you might want to check things out again
